# Site settings
# Site title
title: EmberCrypt Power Station

# Site description
description: Homepage of EmberCrypt BV... Exciting times ahead full of EV battery recycling, off-grid power storage, ...

# Site background
background: "images/background.jpg"

# Site logo
logo: "images/logo.png"

# Countdown clock
# (This can be commented out if not required.)
countdown:
  # format: 
  launch_date: "2025-06-22"
  # %d, %H, %M, %S available
  format: "%d days, %H hours"

# Mailing list subscription
# (This can be commented out if not required.)
#subscribe:
#  action: "https://weightless.so/api/lists/tnbzp9z3/subscribe"

# Social media links
# (This can be commented out if not required.)
#social:
  facebook: "#"
  twitter: "#"
  google: "#"
  instagram: "#"
  pinterest: "#"
  snapchat: "#"
  linkedin: "in/#"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt
