# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://embercrypt.com
title: EmberCrypt
subtitle: "Embedded Security | Reverse Engineering | Side-Channel Attacks"
email: jan@embercrypt.com
author: Jan Van den Herrewegen
description: > # "Write an awesome description for your new site here. 
  Specialised in embedded device security. Security analysisand reverse engineering of Electronic Control Units and various other embedded devices (keyfobs, immobilisers, keyless entry, diagnostics)
copyright: 'Copyright &copy; 2025 Ember Crypt BV. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:jan@embercrypt.com
    fav: envelope
  - title: twitter
    url: https://twitter.com/crypt_ember
    fav: twitter
  - title: git
    url: https://github.com/embercrypt
    fav: github
  - title: pgp
    url: assets/pgp.asc
    fav: lock
